// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVwjaBpjZ3Fx581HIsvqQAzG7fKUjLpyw',
    appId: '1:361357647948:web:12c38d3770f19ace9054e9',
    messagingSenderId: '361357647948',
    projectId: 'platzitripsflutter-ae73d',
    authDomain: 'platzitripsflutter-ae73d.firebaseapp.com',
    storageBucket: 'platzitripsflutter-ae73d.appspot.com',
    measurementId: 'G-7X2BFW0ZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRwyqX5UsRA3Mk32WkIbzMF2eatxWdY18',
    appId: '1:361357647948:android:f5c0b7f3c558849b9054e9',
    messagingSenderId: '361357647948',
    projectId: 'platzitripsflutter-ae73d',
    storageBucket: 'platzitripsflutter-ae73d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIq7fVMNb1-9xiugnxTSOh2i3B_kp_x4',
    appId: '1:361357647948:ios:52c257e5893a2b8a9054e9',
    messagingSenderId: '361357647948',
    projectId: 'platzitripsflutter-ae73d',
    storageBucket: 'platzitripsflutter-ae73d.appspot.com',
    iosBundleId: 'com.example.platziTripApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIq7fVMNb1-9xiugnxTSOh2i3B_kp_x4',
    appId: '1:361357647948:ios:52c257e5893a2b8a9054e9',
    messagingSenderId: '361357647948',
    projectId: 'platzitripsflutter-ae73d',
    storageBucket: 'platzitripsflutter-ae73d.appspot.com',
    iosBundleId: 'com.example.platziTripApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVwjaBpjZ3Fx581HIsvqQAzG7fKUjLpyw',
    appId: '1:361357647948:web:84bcdc8140bc47af9054e9',
    messagingSenderId: '361357647948',
    projectId: 'platzitripsflutter-ae73d',
    authDomain: 'platzitripsflutter-ae73d.firebaseapp.com',
    storageBucket: 'platzitripsflutter-ae73d.appspot.com',
    measurementId: 'G-F74LBZ6WFX',
  );
}
